export {Brand} from "./brand/Brand"
export {Nav} from "./nav/Nav"
export {Depo} from "./depo/Depo"
export {Footer} from "./footer/Footer"
export {Service} from "./service/Service"
export {Techs} from "./techs/Techs"
